### ISSUE TITLE
Maps inside item frames fails to render in multiplayer

### ISSUE THREAD

**Issue by DanielDG10** [Crystal-Nest/soul-fire-d#55]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [ ] I have installed the mod properly

### Current behavior

Maps in item frame fail to render in multiplayer and emits rendering error: 
Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1283)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Invalid entity data item type for field 17 on entity class_745['bumba2201'/218892, l='ClientLevel', x=-1719.50, y=68.00, z=-21.50]: old=0(class java.lang.Integer), new=127(class java.lang.Byte)
	at net.minecraft.class_2945.method_12785(class_2945.java:204)
	at net.minecraft.class_2945.method_12779(class_2945.java:191)
	at net.minecraft.class_634.method_11093(class_634.java:529)
	at net.minecraft.class_2739.method_11808(class_2739.java:46)
	at net.minecraft.class_2739.method_11054(class_2739.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	... 10 more

### Expected behavior

Maps should render correctly

### Steps to reproduce

1.launch the mod with output log on
2. Enter any multiplayer server
3. search for a map in item frame
4. check output log for the rendering error

### Minecraft version

1.20.4

### Mod loader version

Fabric 0.16.5

### Mod version

4.0.3(latest)

### Other mods

Cobweb(Dependency), Forge Config API Port(Dependency), Fabric API(Dependency)

### Stacktrace and logs

Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1283)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Invalid entity data item type for field 17 on entity class_745['bumba2201'/218892, l='ClientLevel', x=-1719.50, y=68.00, z=-21.50]: old=0(class java.lang.Integer), new=127(class java.lang.Byte)
	at net.minecraft.class_2945.method_12785(class_2945.java:204)
	at net.minecraft.class_2945.method_12779(class_2945.java:191)
	at net.minecraft.class_634.method_11093(class_634.java:529)
	at net.minecraft.class_2739.method_11808(class_2739.java:46)
	at net.minecraft.class_2739.method_11054(class_2739.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	... 10 more

### Additional context

![image](https://github.com/user-attachments/assets/74499ced-533e-4a1f-afbb-9454c62efb1b)

**Comment by Crystal-Spider** [comment]
Does the server have the mod installed?

**Comment by DanielDG10** [comment]
> Does the server have the mod installed?

No, it's a vanilla server

**Comment by Crystal-Spider** [comment]
Then it's not a bug, Soul Fire'd is required on both server **and** client.

Please, many issues have been opened about this and they all are because people don't read properly a simple information that is written at the top of the mod page:  
![image](https://github.com/user-attachments/assets/2488d9ef-e6ec-48bb-b83f-cf89f57ceb74)  
Furthermore, at the start of each new opened issue there is a checkbox asking whether you installed the mod on the proper side.

Note: I'm not angry or anything, and certainly I don't hold anything against you, it just so happens that this issue is one of many along the same line and it gets a bit frustrating.
